### ISSUE TITLE
在--config参数存在的时候，其它命令行参数无效

### ISSUE THREAD

**Issue by otakustay** [otakustay/danmaku-to-ass#15]
把两者合并直来会更好些

**Comment by sola97** [comment]
把边框和阴影的宽度、颜色的自定义也加上吧
OutlineColour
BackColour
Outline
Shadow
--config 配置文件里支持就可以了，命令行没需求

**Comment by otakustay** [comment]
升级了一下，你要不试试？ 1.6.1版本，具体可以参考命令行说明或README

如果有兴趣的话顺便分享下你的配置给我吧，我怎么也搞不出好看的，没有审美观的悲剧……

**Comment by sola97** [comment]
```
{
    "fontSize": [25, 25],
    "fontName": "黑体",
    "color": "#ffffff",
    "outlineColor": "#3c3c3c",
    "backColor": "#1e1e1e",
    "outline": 0,
    "shadow": 1,
    "bold": true,
    "padding": [2, 2, 2, 2],
    "playResX": 1920,
    "playResY": 1080,
    "scrollTime": 10,
    "fixTime": 4,
    "opacity": 0.93,
    "bottomSpace": 60,
    "includeRaw": true
}
```

弹幕外观跟字幕渲染器也有关..xysubfilter效果比pot内置的好
http://pan.baidu.com/s/1gfLUFv1
我的屏蔽列表还是有bug

**Comment by sola97** [comment]
屏蔽列表有行数限制..好像30多行就不行了，我把200行缩成1行没问题了

**Comment by otakustay** [comment]
代码里倒没限制，可能数量多了哪里会出问题，回头我用你的那份试一试

**Comment by otakustay** [comment]
@sola97 我看了一下，你的这个规则文件不是UTF-8编码的，所以在读取的时候出错了，程序没办法很正确地检测出文件的编码，所以要求输入都是UTF-8的

如果你搞不定编码的话，建议你`npm install -g file-encoder`然后`file-encoder -t xxx.txt`就能转成UTF-8了

另外你的规则里有几条可能不是你的本意：
1. `^\d+(以内|内|+|点到|!|啊|阿)`这条是肯定会出错的，中间那个`+`不符合正则
2. `[红黄蓝篮绿黑青白紫橙粉][子字色].*|(是|自古|真心).{0,5}`这条屏蔽的范围非常大，弹幕中包含一个“是”字就会被屏蔽，可能不是你想要的，问题大概出在中间那个`|`上
3. `没人`这条范围也比较大，感觉`^没人`会更好一些
4. `逼王|(一二三四五六)级|参见|^[版班办半般板阪舨][本笨苯]`同样只要弹幕中有“版本”或“参见”就会屏蔽，可能范围有点大了
5. `5s|0s|5S|0S|秒|无压力|等我|广告`同理
6. `\d.\d\d`这条规则对数字的屏蔽太厉害，所有年份都不放过……

**Comment by sola97** [comment]
我用虚拟机的，规则直接linux里复制的时候经过了一次剪贴板变ANSI了
Linux里应该是utf-8的，报这个错Invalid attempt to destructure non-iterable instance

**Comment by otakustay** [comment]
嗯这个问题我有发现，刚才忘了说了……等我电脑重装完了就修复

## 

Gray Zhang

在 2016年10月16日 at 下午12:22:58, sola97 (notifications@github.com) 写到:

**Comment by otakustay** [comment]
刚发布的 1.6.2 有修复这个问题，问题的起因是我暴力地认为所有大写字母组合的（如`COLOR`、`TOP`、`BOTTOM`）全是内置规则，但是像"DNF"这种也被当内置组合用，结果没有对应逻辑失败了……

**Comment by sola97** [comment]
更新了，简直完美
