### ISSUE TITLE
部分弹幕xml文件转换出错

### ISSUE THREAD

**Issue by sola97** [otakustay/danmaku-to-ass#16]
我习惯用弹弹play导出的xml文件，遇到过挺多次报错的，可能弹弹play导出有乱码的原因？
https://pan.baidu.com/s/1c26IV0s
比如这个只有神知道的世界第二季01话的弹幕文件，转换的时候会提示
[TypeError: Cannot read property 'replace' of undefined]

**Comment by otakustay** [comment]
已经修复，请更新版本至1.6.3
